export const CREATE_REQUEST = "CREATE_REQUEST";
export const CREATE_SUCCESS = "CREATE_SUCCESS";
export const CREATE_FAIL = "CREATE_FAIL";

export const GET_STUDENT_DATA_REQUEST = "GET_STUDENT_DATA_REQUEST";
export const GET_STUDENT_DATA_SUCCESS = "GET_STUDENT_DATA_SUCCESS";
export const GET_STUDENT_DATA_FAIL = "GET_STUDENT_DATA_FAIL";

export const SINGLE_VIEW_REQUEST = "SIGLE_VIEW_REQUEST";
export const SINGLE_VIEW_SUCCESS = "SINGLE_VIEW_SUCCESS";
export const SINGLE_VIEW_FAIL = "SINGLE_VIEW_FAIL";
