export const CREATE_COURSE_CATEGORY_REQUEST = "CREATE_COURSE_CATEGORY_REQUEST";
export const CREATE_COURSE_CATEGORY_SUCCESS = "CREATE_COURSE_CATEGORY_SUCCESS";
export const CREATE_COURSE_CATEGORY_FAIL = "CREATE_COURSE_CATEGORY_FAIL";
