export const CREATE_COURSE_CATEGORY_REQUEST = "CREATE_COURSE_CATEGORY_REQUEST";
export const CREATE_COURSE_CATEGORY_SUCCESS = "CREATE_COURSE_CATEGORY_SUCCESS";
export const CREATE_COURSE_CATEGORY_FAIL = "CREATE_COURSE_CATEGORY_FAIL";

export const GET_CATEGORY_REQUEST = "GET_CATEGORY_REQUEST";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAIL = "GET_CATEGORY_FAIL";

export const COURSE_CATEGORY_SINGLEVIEW_REQUEST =
  "COURSE_CATEGORY_SINGLEVIEW_REQUEST";
export const COURSE_CATEGORY_SINGLEVIEW_SUCCESS =
  "COURSE_CATEGORY_SINGLEVIEW_SUCCESS";
export const COURSE_CATEGORY_SINGLEVIEW_FAIL =
  "COURSE_CATEGORY_SINGLEVIEW_FAIL";

export const COURSE_CATEGORY_DELETE_REQUEST = "COURSE_CATEGORY_DELETE_REQUEST";
export const COURSE_CATEGORY_DELETE_SUCCESS = "COURSE_CATEGORY_DELETE_SUCCESS";
export const COURSE_CATEGORY_DELETE_FAIL = "COURSE_CATEGORY_DELETE_FAIL";

export const COURSE_CATEGORY_UPDATE_REQUEST = "COURSE_CATEGORY_UPDATE_REQUEST";
export const COURSE_CATEGORY_UPADATE_SUCCESS =
  "COURSE_CATEGORY_UPADATE_SUCCESS";
export const COURSE_CATEGORY_UPDATE_FAIL = "COURSE_CATEGORY_UPDATE_FAIL";
