export const CREATE_COURSE_REQUEST = "CREATE_COURSE_REQUEST";
export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_REQUEST";
export const CREATE_COURSE_FAIL = "CREATE_COURSE_FAIL";

export const GET_COURSE_DATA_REQUEST = "GET_COURSE_DATA_REQUEST";
export const GET_COURSE_DATA_SUCCESS = "GET_COURSE_DATA_SUCCESS";
export const GET_COURSE_DATA_FAIL = "GET_COURSE_DATA_FAIL";

export const COURSE_SINGLE_VIEW_REQUEST = "COURSE_SINGLE_VIEW_REQUEST";
export const COURSE_SINGLE_VIEW_SUCCESS = "COURSE_SINGLE_VIEW_SUCCESS";
export const COURSE_SINGLE_VIEW_FAIL = "COURSE_SINGLE_VIEW_FAIL";

export const DELETE_COURSE_REQUEST = "DELETE_COURSE_REQUEST";
export const DELETE_COURSE_SUCCESS = "DELETE_COURSE_SUCCESS";
export const DELETE_COURSE_FAIL = "DELETE_COURSE_FAIL";

export const UPDATE_COURSE_REQUEST = "UPDATE_COURSE_REQUEST";
export const UPDATE_COURSE_SUCCESS = "UPDATE_COURSE_SUCCESS";
export const UPDATE_COURSE_FAIL = "UPDATE_COURSE_FAIL";
