export const CREATE_COURSE_REQUEST = "CREATE_COURSE_REQUEST";
export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_REQUEST";
export const CREATE_COURSE_FAIL = "CREATE_COURSE_FAIL";

export const GET_COURSE_DATA_REQUEST = "GET_COURSE_DATA_REQUEST";
export const GET_COURSE_DATA_SUCCESS = "GET_COURSE_DATA_SUCCESS";
export const GET_COURSE_DATA_FAIL = "GET_COURSE_DATA_FAIL";

export const COURSE_SINGLE_VIEW_REQUEST = "COURSE_SINGLE_VIEW_REQUEST";
export const COURSE_SINGLE_VIEW_SUCCESS = "COURSE_SINGLE_VIEW_SUCCESS";
export const COURSE_SINGLE_VIEW_FAIL = "COURSE_SINGLE_VIEW_FAIL";
